### ISSUE TITLE
Syntax Error on sending sale to datecs fp700

### ISSUE THREAD

**Issue by ghost** [mitkola/edafpgate#1]
I have been able to connect with the datecs fp700 and test connection using the http://localhost:8182/admin but failing to send sale data for printing of fiscal receipt. 

1st upon trying the given code (or sale format) on the readme I get a syntax error below
`errors [...]
0 1559864806217: 20: Error (cmd: 90): Syntax error
1 1559864806247: 20: Error (cmd: 90): Common error
2 1559864806748: 20: For input string: "00101399,00000058,00102487"
3 1559864806848: 20: Error (cmd: 56): Common error
4 1559864806878: 20: Error (cmd: 56): Unauthorized command in this mode
5 1559864806938: 20: Error (cmd: 56): Error closing fiscal receipt ()!
6 1559864806948: 20: FPError Code: -1 Message: closeFiscalCheck: [General Error, Unauthorized Command in This Mode, Fiscal Bonn Close ()!]`

2nd how can the data correctly formatted or send data to the printer as per attached document, at least i.e open fiscal receipt, register sale and close fiscal receipt
[Printer essential.docx](https://github.com/edabg/fpgate/files/3263975/Printer.essential.docx)

**Comment by mitkola** [comment]
2.0 Branch is with new protocol implementation in corespondense in new regulation in Bulgraria (https://github.com/edabg/fpgate/blob/master/FPGateSrv/doc/Datecs/PM_FISCAL_PRINTERS-BUL-v1_00BG.pdf)
You can try to use versio 1.0 which supports old protocol https://github.com/edabg/fpgate/releases/download/v1.0.5-a/FPGateSrvInstall-1.0.5-a.jar

**Comment by ghost** [comment]
@mitkola thanks, I will give it that a try but I am on an urgent matter. I know the commands to send to the printer as i have tested with a java tool so I would like to how do send commands to the printer directly. 

For example, for the FP700 to initiate a fiscal print I send command number 50 with data like "1,000,2". If I know how to send the commands with data I will be sorted.

**Comment by ghost** [comment]
When I switched to protocol 1, I get 
fperror code:-1 
message: cant find moniker

**Comment by ghost** [comment]
I have been able to send custom command with protocol 2, but when i put a long argument or one with special characters it brings a syntax error

**Comment by mitkola** [comment]
Can you give simple command which you try and how you do actual call?
