### ISSUE TITLE
Sending multiple commands

### ISSUE THREAD

**Issue by ghost** [mitkola/edafpgate#2]
I am sending custom commands to the printer (FP700) in order to print but as they get sent they don't reach the printer sequentially and hence failing print a full receipt. 

How can I order my commands sequentially on the APIs

**Comment by mitkola** [comment]
You can do only with `PrintFiscalCheck` command.

**Comment by ghost** [comment]
How do I do that? I saw the is a "CMD" for custom command but what is the format to put command number and data.

Example I wanted to send command number 40 with xxxx data and 50 with yyyy data
